### ISSUE TITLE
Suggestion: Switch from yaml to json5 for configuration

### ISSUE THREAD

**Issue by jbergens** [packem/packem#5]
Yaml does not seem to be that great, there are still many edge cases, it can be hard to edit if the file is large or without editor support and it is less common than json anyway.

My suggestion would be json5 instead, simplified json and with comments.

https://json5.org/

See here for more info about problems with yaml
https://noyaml.com/

**Comment by undefinedbuddy** [comment]
Your suggestion is appreciated.

1. "still many edge cases". Please do specify.
2. "it can be hard to edit if the file is large". The same could be said about JSON5.
3. "without editor support". Which editors? AFAIK, VSCode, Atom & Sublime Text support YAML by default. As for JSON5, it seems like it's the other way around.
4. "less common than json". True, but how does that make YAML less suitable (in our case)?

For now, we intend to stick to YAML. Perhaps this is something we might develop a plugin for given that enough users request it.
