### ISSUE TITLE
Supporting typescript

### ISSUE THREAD

**Issue by pret-a-porter** [packem/packem#6]
Do you support typescript?
When I search word `typescript` on your site https://packem.github.io/, I get the redirect to https://reactjs.org/docs/static-type-checking.html#typescript

**Comment by undefinedbuddy** [comment]
The site's search functionality is not usable at all as of now. React's site employs its own subscription to Algolia. As for TypeScript support, `@packem/typescript` fails to work with the `onModuleBundle` event hook. Both these issues will be fixed. Thanks for the feedback.

**Comment by undefinedbuddy** [comment]
Anyone who is interested in finding a work around can check this link: https://github.com/packem/packem-plugins/tree/master/typescript-plugin
